// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package server

import (
	"github.com/Ahmad-Magdy/k8s-pod-scheduler/k8s"
	"github.com/Ahmad-Magdy/k8s-pod-scheduler/logger"
	"github.com/Ahmad-Magdy/k8s-pod-scheduler/scheduler"
	"google.golang.org/grpc"
)

// Injectors from wire.go:

func InitializeServer() (*grpc.Server, error) {
	zapLogger := logger.New()
	k8S, err := k8s.New(zapLogger)
	if err != nil {
		return nil, err
	}
	schedulerScheduler := scheduler.New(zapLogger, k8S)
	server := New(zapLogger, schedulerScheduler)

	return server, nil
}
